name: deploy-progress-forum
on:
  push:
    branches: [master, development]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure environment variables for production
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL_PROD }}" >> $GITHUB_ENV
          echo "Added production environment variable(s)"
      - name: Configure environment variables for development
        if: ${{ github.ref == 'refs/heads/development' }}
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL_DEV }}" >> $GITHUB_ENV
          echo "Added development environment variable(s)"

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ">=3.5"

      - run: pip3 install --upgrade pip awsebcli

      - name: Substitute placeholder environment variables with repository-configured values
        run: |
          sed -i.bak "s|secrets\.MONGO_URL|${{ env.MONGO_URL }}|" docker-compose.yml
          sed -i.bak "s|secrets\.SMTP_USER|${{ secrets.SMTP_USER }}|" docker-compose.yml
          sed -i.bak "s|secrets\.SMTP_PASSWORD|${{ secrets.SMTP_PASSWORD }}|" docker-compose.yml
          sed -i.bak "s|secrets\.CLOUDINARY_API_KEY|${{ secrets.CLOUDINARY_API_KEY }}|" docker-compose.yml
          sed -i.bak "s|secrets\.CLOUDINARY_API_SECRET|${{ secrets.CLOUDINARY_API_SECRET }}|" docker-compose.yml
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      - name: Include the modified docker-compose.yml in the to-be-deployed changes
        run: |
          git config --global user.name github_action
          git config --global user.email github_action@github.com
          git add docker-compose.yml

      # - name: Execute deployment
      #   run: eb deploy --verbose --staged --timeout 20
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-west-2"
